### ISSUE TITLE
TestRandomUint64 failures

### ISSUE THREAD

**Issue by johnsonjh** [pkt-cash/pktd#112]
Can trigger reliably when doing extensive regression testing on my system when low on entropy, even when using HAVEGED, and can almost always trigger when doing testing using virtual machines - hard to say what a solution is since tests should either pass or fail, but perhaps we should do some additional verification of what we get back from Rand, in the situations where it's truly warranted?

```
--- FAIL: TestRandomUint64 (0.00s)
    common_test.go:741: Random Uint64 iteration 195 failed - The random number generator on this system is clearly terrible since we got 6 values less than 72057594037927936 in 256 runs when only 5 was expected 6
FAIL
```

```
// TestRandomUint64 exercises the randomness of the random number generator on
// the system by ensuring the probability of the generated numbers.  If the RNG
// is evenly distributed as a proper cryptographic RNG should be, there really
// should only be 1 number < 2^56 in 2^8 tries for a 64-bit number.  However,
// use a higher number of 5 to really ensure the test doesn't fail unless the
// RNG is just horrendous.
```
```
// randomUint64 returns a cryptographically random uint64 value.  This
// unexported version takes a reader primarily to ensure the error paths
// can be properly tested by passing a fake reader in the tests.
func randomUint64(r io.Reader) (uint64, er.R) {
    rv, err := binarySerializer.Uint64(r, bigEndian) 
    if err != nil {
        return 0, err
    }
    return rv, nil
}
    
// RandomUint64 returns a cryptographically random uint64 value.
func RandomUint64() (uint64, er.R) {
    return randomUint64(rand.Reader)
}
```

As an aside, we should investigate current uses of "math/rand" to see if "crypto/rand" might be more appropriate.

**Comment by johnsonjh** [comment]
OK, this clearly is Go being retarded:

> On Linux and FreeBSD, Reader uses getrandom(2) if available, /dev/urandom otherwise. On OpenBSD, Reader uses getentropy(2). On other Unix-like systems, Reader reads from /dev/urandom. On Windows systems, Reader uses the CryptGenRandom API. On Wasm, Reader uses the Web Crypto API. 

On Linux systems, [getrandom(2)](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=c6e9d6f38894798696f23c8084ca7edbf16ee895) should allow for configurable behavior via GRND_RANDOM, but Go seems do the wrong thing for crypto and sets GRND_NONBLOCK, so rather than blocking, the call fails, and thus, the test fails.

According to [reliable sources](https://lwn.net/Articles/525459/), for CSPRNG purposes, you really **do** want to block when the entropy pool is low or empty, thus the use of `/dev/random` or `getrandom` without `GRND_NONBLOCK` set would be much more appropriate for "crypto/random". They could still leave `/dev/urandom` for "math/random".

Though it's been the point of much arguing and probably breaking up some marriages, GnuPG (which I consider to be a benchmark) will block on low-entropy situations, and uses /dev/random where available.  The latest GnuPG 2 [still insists that /dev/random is the way to go for crypto purposes](https://github.com/gpg/gnupg/blob/7fc3decc2e038be905d47701c7ce196ed86a725b/doc/faq.org#which-random-data-gatherer-should-i-use).

(Note that https://www.2uo.de/myths-about-urandom/ is itself a myth and full of unreliable information - one only needs to look at the current man pages to verify.)

**Comment by johnsonjh** [comment]
Currently recompiling my Go runtime to **not** set `GRND_NONBLOCK` and to fall-back to `/dev/random`.

**Comment by johnsonjh** [comment]
New runtime built with these changes:

```
-const urandomDevice = "/dev/urandom"
+const urandomDevice = "/dev/random"
```
```
-       GRND_NONBLOCK GetRandomFlag = 0x0001
+       //GRND_NONBLOCK GetRandomFlag = 0x0001
```

And now, firing off 25,000 tests.

**Comment by johnsonjh** [comment]
~38 hours and we'll know how it went.

**Comment by cjdelisle** [comment]
That test is stupid.

Firstly, if you run it long enough with a correct CSPRNG it will eventually fail. A CSPRNG *can* give you any string of numbers you imagine, and if you keep testing it long enough, it will. What you did was essentially that.

Furthermore, if there was an actual problem with system entropy, you wouldn't see "skewed random numbers", you'd see the same sequence of random numbers from one run to another, something you cannot effectively test for.

> The latest GnuPG 2 still insists that /dev/random is the way to go for crypto purposes.
They also think GPG is usable

* Delete the test
* Use /dev/urandom
* Ignore the cryptonerds

**Comment by johnsonjh** [comment]
I use GnuPG every day, it's gotten much better since 2.2 and integration with the system keychain (ie 'Secret Service Integration'), and I'm still in the /dev/random camp, but I agree with you the test is stupid :+1: 

I've not been able to trigger it with my patched cryptonerd approved runtime yet, but normally a full run (25,000 cycles) takes about 41 hours... 

But anyway, I'm with you on deleting the test, it's useless.

**Comment by johnsonjh** [comment]
[There you are.](https://github.com/pkt-cash/pktd/pull/114)

**Comment by johnsonjh** [comment]
We can close this since you merged #114

**Comment by johnsonjh** [comment]
Just to let you know, my *cryptonerd-approved* Go runtime patched with:

```
-const urandomDevice = "/dev/urandom"
+const urandomDevice = "/dev/random"
```
```
-       GRND_NONBLOCK GetRandomFlag = 0x0001
+       //GRND_NONBLOCK GetRandomFlag = 0x0001
```
Did manage to complete more than 25,000 cycles without the error - before, I could trigger it reliably; still a pretty useless test, glad it's gone.

**Comment by johnsonjh** [comment]
Closing due to issue resolved.
