### ISSUE TITLE
Update some dependencies with notable bugfixes

### ISSUE THREAD

**Issue by johnsonjh** [pkt-cash/pktd#15]
A few module dependencies can be safely updated, especially as there are quite a few important bugfixes to the grpc module. Also ran through go tidy to ensure any indirect modules that might be required for other platforms correctly resolve and would be included (no issues).

Tested here for ~24 hours under moderate conditions without incident. 

Attached: [Diff formatted patch file](https://github.com/pkt-cash/pktd/files/4808921/deps.txt)

**Comment by cjdelisle** [comment]
1. Pulling the update to bbolt
2. Update to lnd/queue is ahead of upstream ( https://github.com/lightninglabs/neutrino/blob/master/go.mod#L11 ), skipping
3. Accepting grpc update which should be safe - we are already diverged from btcwallet there
4. Accepting golang.org/x/crypto - probably safe
5. Updating bbolt to exactly the version used in btcwallet
6. Dropping indirect dependencies which were added

There was a `replace` reference loop at the end of your go.mod file, I'm not sure how it built - or if it built then which implementation was being used - but it was not correct.
