### ISSUE TITLE
Possible fix for incorrectly orphaned transactions from mainline btcd

### ISSUE THREAD

**Issue by johnsonjh** [pkt-cash/pktd#17]
Attached: [diff](https://patch-diff.githubusercontent.com/raw/btcsuite/btcd/pull/1526.diff)

Looks promising as the cause of the orphaned txn issue.

**Comment by johnsonjh** [comment]
patch will apply with massaging, needs to be ported to cjd's new error handling.

**Comment by cjdelisle** [comment]
I will adapt and merge this but unfortunately it won't solve the issue which we are having. Thanks for finding it though !

**Comment by cjdelisle** [comment]
Done in 288909ff
