### ISSUE TITLE
The future of BTC Core/Satoshi compatibility, BIP-0155, BIP-0152, ADDVR2, etc.

### ISSUE THREAD

**Issue by johnsonjh** [pkt-cash/pktd#248]
* See Core commit https://github.com/bitcoin/bitcoin/commit/7be6ff61875a8d5d2335bff5d1f16ba40557adb0
  * I see we'll have to recognize and ignore the I2P names on P2PNET to maintain full compatibility with Core mainnet,  if that's going to remain a goal - I'm currently of the opinion that we should move away for that, as the effort to get *"there"* from *"here"* would be quite large and mostly, IMHO, wasted effort, and our time best spent elsewhere.

I have a list, somewhere, of the changes needed to maintain full interop with Core mainnet, and it's getting longer every day. 

The changes are coming very fast from Core lately, like the entire new ban system being dropped and replaced with the new "discouragement" logic, all in a point release, and before I could even get the 0.19.x/0.20.0 behavior cloned and merged. 

Even upstream BTCD, back under active development, [is no longer compatible](https://github.com/btcsuite/btcd/issues/1661) with BTC Core mainnet right now. Unsurprisingly, due to the issues we (@johnsonjh and @cjdelisle) had previously taked about privately. 

In this case, you see the Satoshi/Core and BTCD get in a fight because BTCD does not (yet) implement *addrv2* wire messages aka [BIP-0155](https://github.com/bitcoin/bips/blob/master/bip-0155.mediawiki), and Core does not recognize the wire *reject* messages - they've already been purged from their network, with the result being disconnected (and now, eventual isolation from the network via the discouragement mechanism and peers won't connect to you).  

I propose we start looking more to BCH/BCHN/BCHA (Bitcoin Cash), not for direct interoperability, but as a source for maintaining the "state of the art" when it comes to effectively communicating on the P2P mainnet. In fact, the aggressive changes being pushed (by only a few influential developers in many cases) seems to be in response to falling behind some of the forks, and they often offer less complex and dangerous alternatives to some of the changes being pushed in Core.

So, while they aren't actively "banning" any longer on Core P2P mainnet, it's now very easy to end up as an isolated peer unless we go along with all the rest of the Core changes like removal of reject, alterts, banning, HBCBR, compressed representation, Schnorr signatures, ADDVR2 - the list keeps getting longer. Also, just to give one example, nodes that run as HBCBR (High-Bandwidth Compact Block Relays) aka [BIP-0152](https://github.com/bitcoin/bips/blob/master/bip-0152.mediawiki) will be exempted from the "discouragement"/shunning system.

Also, while not *unsound*, I believe that many of these new changes in Core are *dangerous* because they're difficult to get right, and getting them wrong would create an incident.  I'd present [BIP-0152 Pre-Validation Relay](https://github.com/bitcoin/bips/blob/master/bip-0152.mediawiki#PreValidation_Relay_and_Consistency_Considerations) as just one example of many. A system essentially the same as [FIBRE](https://bitcoinfibre.org/) (*Fast Internet Bitcoin Relay Extension*) is in use on the BCH network, and does not change the block validation logic. Also, extensions such as XTHINNER are options we can explore without much systemic risk to the network, and always having to up to date with the, of late, relentless changes in Core.

We can also maintain connectively with Core, if necessary, by adopting a compatible Lightning implementation that offers a channel compatible with Satoshi/Core Bitcoind, or connecting PKTD directly to a BTCD node manually (thus a persistent and white-listed link) seems to be a more reasonable goal at this time.  Again, my opinion only.

**Comment by johnsonjh** [comment]
FYI I currently have compatibility (at least, silent ignoring to enable non-annoying interop) with TORV2 and TORV3 netnames as a pending PR. We've already adopted the disconnect policies and wire protocol changes from Core, through my previous PR's, and 

I also have an initial implementation of the new packed encoding, Schnorr signature/multisig, and ADDRV2 support in my tree at this time - but I'm certainly not going to implement things like HBCBR-PVR, and I have no desire to track their commits and releases, especially when I already have a FIBRE-like solution based on KCP almost ready to go, and some other changes such as increased wire limits for inv transfers that essentially come right from BCH.

**Comment by vasild** [comment]
> ... because BTCD does not (yet) implement addrv2 wire messages aka BIP-0155 ...

Actually the reason for the disconnect is that btcd disconnects when it receives any message which it does not recognize. If it just ignores unknown messages, then everything will work fine. No need to implement anything.

**Comment by johnsonjh** [comment]
> Actually the reason for the disconnect is that btcd disconnects when it receives any message which it does not recognize. If it just ignores unknown messages, then everything will work fine. No need to implement anything.

We're doing that in our develop branch... I wonder how long it will be, though, before Core starts to increase "discouragement" scores for sending "invalid" wire messages like `reject`
