### ISSUE TITLE
Issue restoring old wallet after successful decryption

### ISSUE THREAD

**Issue by Strykar** [pkt-cash/pktd#384]
I can decrypt the wallet but `pktctl --wallet getbalance` always shows `0`.
The [blockchain explorer](https://packetscan.io/address/pkt1qyt8sugekynh3wjj4vvnnkplfkc3v7fewxejfh4) shows a few thousand PKT for the same address.

Wallet re-creation:
```
$ ./bin/pktwallet --create
Enter the private passphrase for your new wallet: 
Confirm passphrase: 
Do you have an existing wallet seed you want to use? (n/no/y/yes) [no]: yes
Enter existing wallet seed: My 15 word seed
This seed was taken from a wallet protected by a password.
Enter the wallet password now: 
Decrypting your seed...
Creating the wallet...
The wallet has been created successfully.
```

Wallet synced
```
$ ./bin/pktwallet
1726069968 [INF] pktwallet.go:67 Version 1.7.0
1726069968 [INF] server.go:200 Listening on 127.0.0.1:64763
1726069968 [INF] seed.go:58 9 addresses found from DNS seed seed.cjd.li
1726069968 [INF] seed.go:58 5 addresses found from DNS seed pktdseed.pkt.world
1726069968 [INF] blockmanager.go:395 New valid peer [144.76.71.211:64764] (/btcwire:0.5.0/pktd:1.6.1-dirty/)
1726069968 [INF] blockmanager.go:423 Requesting headers from [144.76.71.211:64764]
1726069968 [INF] blockmanager.go:2077 Syncing to block height [2668042] from peer [144.76.71.211:64764]
1726069968 [INF] blockmanager.go:2110 Requesting headers from [144.76.71.211:64764]
1726069968 [INF] blockmanager.go:395 New valid peer [[2001:470:7899:1::7]:64764] (/btcwire:0.5.0/pktd:1.0.1-dirty/)
1726069968 [INF] blockmanager.go:395 New valid peer [[2001:470:7899:1::7]:64764] (/btcwire:0.5.0/pktd:1.0.1-dirty/)
1726069968 [INF] blockmanager.go:395 New valid peer [[2001:470:7899:1::7]:64764] (/btcwire:0.5.0/pktd:1.0.1-dirty/)
1726069969 [INF] wallet.go:3347 Opened wallet
1726069969 [INF] wallet.go:424 Waiting for chain backend to sync to tip

1726069969 [INF] blockmanager.go:395 New valid peer [23.147.168.131:64764] (/btcwire:0.5.0/pktd:1.0.0/)
1726069969 [INF] blockmanager.go:458 Lost peer [144.76.71.211:64764]
1726069969 [INF] blockmanager.go:2077 Syncing to block height [2668042] from peer [[2001:470:7899:1::7]:64764]
1726069969 [INF] blockmanager.go:2110 Requesting headers from [[2001:470:7899:1::7]:64764]
1726069969 [INF] seed.go:58 22 addresses found from DNS seed seed.pkt.ai
1726069969 [INF] seed.go:58 5 addresses found from DNS seed seed.pkt.pink
1726069969 [INF] blockmanager.go:2361 Headers from [[2001:470:7899:1::7]:64764] height: [2668038] checking [5] PacketCrypt proofs of total [5] headers
1726069978 [WRN] blockmanager.go:599 Unable to fetch set of candidate checkpoints, trying again...
1726070002 [INF] wallet.go:428 Chain backend synced to tip! 👍
```

Wallet balance shows empty:
```
$ ./bin/pktctl --wallet getbalance
0
$ ./bin/pktctl --wallet getaddressbalances
[]
$ ./bin/pktctl --wallet getwalletseed
CORRECT 15 word seed shown
```
What am I missing here?

**Comment by UCIS** [comment]
If you're restoring a wallet from seed, you have to manually recreate the addresses (getnewaddress) and then initiate a resync. The Pkt.world wallet (https://www.pkt.world/wallet) provides some GUI options for that (via the Import addresses from seed and Maintenance menus).

**Comment by Strykar** [comment]
Mind elaborating on how it could be done using pktwallet-cli instead of a 3rd party wallet?

**Comment by UCIS** [comment]
As the author of the Pkt.world wallet, I can more easily help you with that wallet. However, if you prefer to use the CLI wallet, I often find the `./bin/pktctl --wallet help` command to be helpful. You will find the `getnewaddress` (I think) command there, which you have to use one or multiple times to create the original addresses again (they will be created in the original order), and then there's a `(begin)resync` command which you can use to instruct the wallet to re-scan the blockchain for relevant transactions. You should not have to provide any arguments to those commands, unless you used legacy format addresses (unlikely) or the wallet does not correctly detect the wallet creation timestamp (shouldn't happen, but in that case you can specify a start block of 0 for the resync command). I think the `getinfo` RPC can be used to check the resync progress, it will show some fields like `maintenanceHeight` and `currentTipHeight` and `maintenanceInProgress` which provide some clues on the synchronization process. Once this is done it should reliably show your wallet balance.

**Comment by Strykar** [comment]
Thank you, running `getnewaddress` and then `resync` seems to have done it, mostly.
It's still approximately 135 PKT short, but most of it shows with `pktctl --wallet getbalance`.

Cheers!

**Comment by Strykar** [comment]
Took another `resync`, but now all the tokens show, thanks very much @UCIS!
