### ISSUE TITLE
With go-devel (a29dd1f2bd Wed Oct 21), new TestNetworkFailure in connmanager_test.go and a fix.

### ISSUE THREAD

**Issue by johnsonjh** [pkt-cash/pktd#82]
--- FAIL: TestNetworkFailure (0.09s)                  
    connmanager_test.go:382: network failure: unexpected number of dials - got 114, want < 75
FAIL                                                                                                                                
FAIL    github.com/pkt-cash/pktd/connmgr        0.261s                                                                              

Updating to the x/net dependency to v0.0.0-20201021035429-f5854403a974 or higher results in passing tests.

I'll push a PR for this, but I've not personally done my normal regression testing to ensure that x/net 20201021035429 doesn't cause any issues with Go 1.14 through 1.15.3 - while I imagine it would not, I've been surprised before!

Edit: Verified this causes no issues with Go toolchains 1.14 through 1.15.3. Also was recommended to me that x/sys be updated when updating x/net, so that will be included. Rebased, so the PR will be against your current develop branch at the time of this writing.

**Comment by johnsonjh** [comment]
Also was recommended to me that x/sys be updated when updating x/net, so that will be included. 
Freebasing, so the PR will be against your current develop branch at the time of this writing.

**Comment by johnsonjh** [comment]
Fix is in PR #84 as promised.

**Comment by johnsonjh** [comment]
Verified this causes no issues with toolchains 1.14 through 1.15.2

**Comment by cjdelisle** [comment]
Can be closed ?

**Comment by johnsonjh** [comment]
> Can be closed ?

Yes, because I can't count or something.

This is fixed in #82 (not #84) which I see you merged. :+1:
